kind: ClusterServingRuntime
apiVersion: serving.kserve.io/v1alpha1
metadata:
  name: nvidia-nim-llama3-8b-instruct-1.0.3
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8000"
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
  containers:
    - image: {{ .Values.llm.image.repository }}:{{ .Values.llm.image.tag }}
      name: kserve-container
      env:
      - name: NIM_CACHE_PATH
        value: /mnt/models
      ports:
      - containerPort: 8000
        protocol: TCP
      resources:
        limits:
          cpu: "12"
          memory: 32Gi
          nvidia.com/gpu: 1
        requests:
          cpu: "12"
          memory: 32Gi
          nvidia.com/gpu: 1
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
  protocolVersions:
  - v2
  - grpc-v2
  supportedModelFormats:
  - autoSelect: true
    name: nvidia-nim-llama3-8b-instruct
    priority: 1
    version: 1.0.3
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 16Gi    
    name: dshm
